# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Cross-Platform-TODO-List' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Cross-Platform-TODO-List
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Auth'

end
